apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: quarkus-app
  template:
    metadata:
      labels:
        deployment: quarkus-app
        service: quarkus
    spec:
      containers:
        - name: quarkus-container
          image: openjdk:17
          env:
            - name: QUARKUS_LAUNCH_DEVMODE
              value: "true"
          command:
            ["/bin/sh", "-c", "java -jar /app/quarkus-app/quarkus-run.jar"]
          volumeMounts:
            - name: quarkus-volume
              mountPath: "/app"
        - name: postgres-container
          image: postgres:latest
          volumeMounts:
            - name: postgres-volume
              mountPath: "/var/lib/postgresql/data"
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "12341234"
            - name: POSTGRES_DB
              value: "books"
      volumes:
        - name: quarkus-volume
          hostPath:
            path: /mnt/c/Users/psousaesilva/Documents/quarkus-books/code-with-quarkus/target
        - name: postgres-volume
          hostPath:
            path: /mnt/c/Users/psousaesilva/Documents/quarkus-books/code-with-quarkus/bd